name: Test

on:
  push:

jobs:
  test:
    name: Test (Node ${{ matrix.node-version}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20]
    steps:
      - uses: actions/checkout@v4
      # v4 だと PostAction が遅すぎて話にならないので v3 を使う
      # see: https://github.com/actions/setup-node/issues/878
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn
      - run: yarn test
